<a href="https://colab.research.google.com/github/vignesh4836/edatheoda1/blob/main/edatheoda1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("https://raw.githubusercontent.com/salemprakash/EDA/main/Data/USSeatBelts.csv")

In [ ]:
df.shape

(765, 13)

In [ ]:
df.head()

,rownames,state,year,miles,fatalities,seatbelt,speed65,speed70,drinkage,alcohol,income,age,enforce
0,1,AK,1983,3358,0.044669,NaN,no,no,yes,no,17973,28.234966,no
1,2,AK,1984,3589,0.037336,NaN,no,no,yes,no,18093,28.343542,no
2,3,AK,1985,3840,0.033073,NaN,no,no,yes,no,18925,28.372816,no
3,4,AK,1986,4008,0.025200,NaN,no,no,yes,no,18466,28.396652,no
4,5,AK,1987,3900,0.019487,NaN,no,no,yes,no,18021,28.453251,no

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 765 entries, 0 to 764
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rownames    765 non-null    int64
 1   state       765 non-null    object
 2   year        765 non-null    int64
 3   miles       765 non-null    int64
 4   fatalities  765 non-null    float64
 5   seatbelt    556 non-null    float64
 6   speed65     765 non-null    object
 7   speed70     765 non-null    object
 8   drinkage    765 non-null    object
 9   alcohol     765 non-null    object
 10  income      765 non-null    int64
 11  age         765 non-null    float64
 12  enforce     765 non-null    object
dtypes: float64(3), int64(4), object(6)
memory usage: 77.8+ KB

In [ ]:
df.describe()

,rownames,year,miles,fatalities,seatbelt,income,age
count,765.000000,765.00000,765.000000,765.000000,556.000000,765.000000,765.000000
mean,383.000000,1990.00000,41447.734641,0.021490,0.528852,17992.586928,35.137194
std,220.980768,4.32332,43961.990037,0.006171,0.170186,4811.459296,1.698131
min,1.000000,1983.00000,3099.000000,0.008327,0.060000,8372.000000,28.234966
25%,192.000000,1986.00000,11401.000000,0.017341,0.420000,14266.000000,34.387501
50%,383.000000,1990.00000,30319.000000,0.021199,0.550000,17624.000000,35.391766
75%,574.000000,1994.00000,52312.000000,0.024774,0.650000,21080.000000,36.130787
max,765.000000,1997.00000,285612.000000,0.045470,0.870000,35863.000000,39.169582

In [ ]:
df.isnull().sum()

rownames        0
state           0
year            0
miles           0
fatalities      0
seatbelt      209
speed65         0
speed70         0
drinkage        0
alcohol         0
income          0
age             0
enforce         0
dtype: int64